// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pgrepo

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type StockHistory struct {
	CreatedAt      pgtype.Timestamp `json:"createdAt"`
	UpdatedAt      pgtype.Timestamp `json:"updatedAt"`
	DeletedAt      pgtype.Timestamp `json:"deletedAt"`
	ID             int32            `json:"id"`
	WarehouseID    uuid.UUID        `json:"warehouseId"`
	ProductID      uuid.UUID        `json:"productId"`
	QuantityChange int32            `json:"quantityChange"`
	OperationType  string           `json:"operationType"`
}

type StockReservation struct {
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
	UpdatedAt        pgtype.Timestamp `json:"updatedAt"`
	DeletedAt        pgtype.Timestamp `json:"deletedAt"`
	ID               uuid.UUID        `json:"id"`
	WarehouseStockID uuid.UUID        `json:"warehouseStockId"`
	OrderID          uuid.UUID        `json:"orderId"`
	Quantity         int32            `json:"quantity"`
}

type TemplateTable struct {
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
	DeletedAt pgtype.Timestamp `json:"deletedAt"`
}

type Warehouse struct {
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	UpdatedAt    pgtype.Timestamp `json:"updatedAt"`
	DeletedAt    pgtype.Timestamp `json:"deletedAt"`
	ID           uuid.UUID        `json:"id"`
	Name         string           `json:"name"`
	LocationID   uuid.UUID        `json:"locationId"`
	LocationName string           `json:"locationName"`
	Capacity     int32            `json:"capacity"`
}

type WarehouseStock struct {
	CreatedAt         pgtype.Timestamp `json:"createdAt"`
	UpdatedAt         pgtype.Timestamp `json:"updatedAt"`
	DeletedAt         pgtype.Timestamp `json:"deletedAt"`
	ID                uuid.UUID        `json:"id"`
	WarehouseID       uuid.UUID        `json:"warehouseId"`
	ProductID         uuid.UUID        `json:"productId"`
	AvailableQuantity int32            `json:"availableQuantity"`
	ReservedQuantity  int32            `json:"reservedQuantity"`
}
