// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pgrepo

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	Createdat  pgtype.Timestamp `json:"createdat"`
	Updatedat  pgtype.Timestamp `json:"updatedat"`
	Deletedat  pgtype.Timestamp `json:"deletedat"`
	ID         uuid.UUID        `json:"id"`
	CustomerID uuid.UUID        `json:"customerId"`
	OrderDate  pgtype.Timestamp `json:"orderDate"`
	Status     string           `json:"status"`
	Total      pgtype.Numeric   `json:"total"`
}

type OrderItem struct {
	Createdat   pgtype.Timestamp `json:"createdat"`
	Updatedat   pgtype.Timestamp `json:"updatedat"`
	Deletedat   pgtype.Timestamp `json:"deletedat"`
	ID          int32            `json:"id"`
	OrderID     uuid.UUID        `json:"orderId"`
	ProductID   int32            `json:"productId"`
	ProductName string           `json:"productName"`
	Quantity    int32            `json:"quantity"`
	Price       pgtype.Numeric   `json:"price"`
}

type TemplateTable struct {
	Createdat pgtype.Timestamp `json:"createdat"`
	Updatedat pgtype.Timestamp `json:"updatedat"`
	Deletedat pgtype.Timestamp `json:"deletedat"`
}
