// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pgrepo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	Createdat   pgtype.Timestamp `json:"createdat"`
	Updatedat   pgtype.Timestamp `json:"updatedat"`
	Deletedat   pgtype.Timestamp `json:"deletedat"`
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Price       pgtype.Numeric   `json:"price"`
}

type ProductStock struct {
	Createdat   pgtype.Timestamp `json:"createdat"`
	Updatedat   pgtype.Timestamp `json:"updatedat"`
	Deletedat   pgtype.Timestamp `json:"deletedat"`
	ProductID   int32            `json:"productId"`
	WarehouseID int32            `json:"warehouseId"`
	StockLevel  pgtype.Int4      `json:"stockLevel"`
}

type TemplateTable struct {
	Createdat pgtype.Timestamp `json:"createdat"`
	Updatedat pgtype.Timestamp `json:"updatedat"`
	Deletedat pgtype.Timestamp `json:"deletedat"`
}
