version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ewallet
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  redis:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    restart: always
    networks:
      - ecommerce-network

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: secret
      DB_NAME: ewallet
    command: >
      sh -c "
        ./wait-for-it.sh db &&
        dbmate -d infra/database/postgres/migrations/ up &&
        /ewallet
      "
    networks:
      - ecommerce-network

volumes:
  db-data:

networks:
  ecommerce-network:
  