// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pgrepo

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Oauth2Client struct {
	ID           int32     `json:"id"`
	ClientID     uuid.UUID `json:"clientId"`
	ClientSecret uuid.UUID `json:"clientSecret"`
	Domain       string    `json:"domain"`
	RedirectUrl  string    `json:"redirectUrl"`
	Scope        []string  `json:"scope"`
}

type Oauth2Token struct {
	ID           int32            `json:"id"`
	AccessToken  string           `json:"accessToken"`
	RefreshToken pgtype.Text      `json:"refreshToken"`
	ExpiresAt    pgtype.Timestamp `json:"expiresAt"`
	ClientID     uuid.UUID        `json:"clientId"`
	UserID       uuid.UUID        `json:"userId"`
}

type TemplateTable struct {
	Createdat pgtype.Timestamp `json:"createdat"`
	Updatedat pgtype.Timestamp `json:"updatedat"`
	Deletedat pgtype.Timestamp `json:"deletedat"`
}

type User struct {
	Createdat pgtype.Timestamp `json:"createdat"`
	Updatedat pgtype.Timestamp `json:"updatedat"`
	Deletedat pgtype.Timestamp `json:"deletedat"`
	ID        uuid.UUID        `json:"id"`
	Email     string           `json:"email"`
	Phone     string           `json:"phone"`
	Password  string           `json:"password"`
	Role      int16            `json:"role"`
}
